import "reflect-metadata";
export { BotFactory as default } from "@/botFactory";
export { default as Module } from "@/decorators/module";
export { default as Controller } from "@/decorators/controller";
export { default as Provider } from "@/decorators/provider";
export { default as Command } from "@/decorators/controller/command";
export { type CommandContext } from "@/decorators/controller/command";
export { default as Arg, BaseArgumentType } from "@/decorators/controller/command/arg";
export { ConsoleLogger, type ConsoleLoggerOptions, type LoggerLike, LogLevel } from "@/logger";
export { ReplyWithError } from "@/errors";
export { type ArgumentsParser } from "@/interfaces/argumentsParser";
